In [23]:
import numpy as np

Método da Potência

In [24]:
def m_potencia(A, y0, k):
    n = len(A)

    z = A @ y0 # Produto de Matrizes
    for i in range(1, k):
        alpha = z[0]
        for j in range(0, n):  # Máxima componente
            if z[j] > alpha: alpha = z[j]

        y = z/alpha
        z = A @ y

    return alpha


def m_potencia_inv(A, y0, k):
    A_inv = np.linalg.inv(A)
    n = len(A)

    z = A_inv @ y0 # Produto de Matrizes
    for i in range(1, k):
        alpha = z[0]
        for j in range(0, n):  # Máxima componente
            if z[j] > alpha: alpha = z[j]

        y = z/alpha
        z = A_inv @ y

    return 1/alpha

In [25]:
A = np.array([[2,1,0], [2,5,3], [0,1,6]])

y0 = np.array([1,1,1])


maior = m_potencia(A, y0, 100)
menor = m_potencia_inv(A, y0, 100)
print(maior)
print(menor)



7.444374823657817
1.3375351956376105


Método QR

In [26]:
from numpy.linalg import qr

A = [[2, 1, 0],
     [2, 5, 3],
     [0, 1, 6]]

Q, R = qr(A) # Obtendo as matrizes Q, R


def autovalores_qr(MatrizA, Q, R, precisao):
    
    An = np.copy(MatrizA)

    # Iterando até obter a diagonal com autovalores
    maior = precisao + 1.0
    while (maior > precisao):
        # Obtendo o maior valor absoluto de A
        maior = abs(An[1][0])  
        for i in range(0, len(An)):
            for j in range(0, len(An)):
                if (i > j):
                    if (abs(An[i][j]) > maior):
                        maior = abs(An[i][j])
        
        An = np.dot(R, Q)  # Próximo A
        Q, R = qr(An) # Novos Q, R

    print(An)
    # Obtendo os autovetores
    Autovalores = []
    for i in range(0, len(An)):
        for j in range(0, len(An)):
            if (i == j):
                Autovalores.append(An[i][j])
    

    return Autovalores
    
    
Autov = autovalores_qr(A, Q, R, 0.0001)
print(Autov)

[[ 7.44434930e+00  1.66260729e+00 -1.47177101e+00]
 [ 4.95308687e-05  4.21811551e+00  2.64181349e-01]
 [ 0.00000000e+00 -4.04568854e-10  1.33753520e+00]]
[7.44434929862239, 4.218115505777112, 1.337535195600506]


In [27]:
autova, autovet = np.linalg.eig(A)

print(autova)
print(autovet)

[1.3375352  4.21808998 7.44437482]
[[ 0.82787594  0.36589541  0.1493214 ]
 [-0.54843867  0.81158895  0.81296166]
 [ 0.11762848 -0.45546012  0.56284674]]
