In [93]:
import numpy as np
from numpy.linalg import qr

Problema das Molas Acopladas

In [94]:
# A1 = 0.75
# A2 = 0.38
# A3 = 0.45
m = 0.5
k = 0.35


Matriz = np.array([[(2*k)/m, (-k)/m, (-k)/m],
          [(-k)/m, (2*k)/m, (-k)/m],
          [(-k)/m, (-k)/m, (2*k)/m]])

# Autovetor = [A1, A2, A3]

In [95]:
def m_potencia(A, y0, iteracoes):
    n = len(A)

    z = A @ y0 # Produto de Matrizes
    for i in range(1, iteracoes):
        alpha = z[0]
        for j in range(0, n):  # Máxima componente
            if z[j] > alpha: alpha = z[j]

        y = z/alpha
        z = A @ y

    return alpha


def autovalores_qr(MatrizA, Q, R, precisao):
    
    An = np.copy(MatrizA)

    # Iterando até obter a diagonal com autovalores
    maior = precisao + 1.0
    while (maior > precisao):
        # Obtendo o maior valor absoluto de A
        maior = abs(An[1][0])  
        for i in range(0, len(An)):
            for j in range(0, len(An)):
                if (i > j):
                    if (abs(An[i][j]) > maior):
                        maior = abs(An[i][j])
        
        An = R @ Q  # Próximo A
        Q, R = qr(An) # Novos Q, R

    
    # Obtendo os autovetores
    Autovalores = []
    for i in range(0, len(An)):
        for j in range(0, len(An)):
            if (i == j):
                Autovalores.append(An[i][j])
    

    return Autovalores

In [96]:
# Descobrindo o maior autovalor

y0 = np.array([-1, -1, 1])

mautov = m_potencia(Matriz, y0, 100)
print(mautov)

2.1


In [97]:
# Descobrindo todos os autovalores

Q, R = qr(Matriz) # Obtendo as matrizes Q, R
autovalores = autovalores_qr(Matriz, Q, R, 0.001)
print(autovalores) # [2.1, 2.1, 0]

[2.1, 2.0999999999999996, -1.00222348398871e-17]


In [98]:
# Calculando a frequência:

frequencia = np.sqrt(mautov)
print(frequencia)

1.449137674618944


In [99]:
autova, autovet = np.linalg.eig(Matriz)

print(autova)

[2.10000000e+00 3.25999283e-17 2.10000000e+00]


Bônus: Calculando as Amplitudes

In [100]:
# As Amplitudes são os autovetores da matriz A:

print(autovet)

[[ 0.81649658 -0.57735027  0.10126028]
 [-0.40824829 -0.57735027 -0.75227804]
 [-0.40824829 -0.57735027  0.65101775]]
